#!/usr/bin/env bash

# Vault Playground V2.1.1 creds
#
# This is a helper task that looks in the cache for any initialization dumps from the currently running Vault instance
# and outputs them to the screen.
#

: "${VP_NAMESPACE:=vp}" # Namespace for the local Vault playground, used for network and container names

vp_init_cache=$HOME/.vault-playground/init_dumps

if [ ! $(command -v docker) ]; then
  echo -e "\ndocker not found! It must be installed before proceeding\n"
  exit 1
fi

if [ ! $(command -v jq) ]; then
  echo -e "\njq not found! It must be installed before proceeding\n"
  exit 1
fi

vault_short_id=$(docker ps -q -f name=${VP_NAMESPACE}-vault1)
vault_init_dump_path=${vp_init_cache}/${vault_short_id}.json
if [ -e "${vault_init_dump_path}" ]; then
  echo "Found cached creds file: $vault_init_dump_path"
  jq . ${vault_init_dump_path}
else
  echo "No cached initialization credentials could be found for the currently running vault instance, or no vault instance is running."
fi
