#!/usr/bin/env bash

# Vault Playground V2.0.0 destroy
#
# This script terminates and removes all containers deployed in the Vault Playground docker network (vp).
#

vp_network_name=vp

if [ ! $(command -v docker) ]; then
  echo -e "\ndocker not found! It must be installed before proceeding: https://www.docker.com/get-docker\n"
  exit 1
fi

containers_to_destroy=$(docker ps -qa --no-trunc -f network=${vp_network_name})

if [ ${#containers_to_destroy} != 0 ]; then
  docker rm -f ${containers_to_destroy}
  docker network rm ${vp_network_name}
else
  echo "No containers found in network or network does not exist. Maybe everything was already destroyed?"
fi

echo "To purge all cached data run the purge script"