#!/usr/bin/env bash

# Vault Playground V.2.1.0 purge
#
# This script deletes all cached credentials and snapshots by removing the $HOME/.vault-playground directory
#

vp_cache=$HOME/.vault-playground

if [ -e ${vp_cache} ]; then
  rm -r ${vp_cache}
fi

echo "Vault Playground cache ($vp_cache) purged"