#!/usr/bin/env bash

# Vault Playground V3.0.0 status
#
# This is a helper task that makes a call to docker ps with relevant filters applied
#

: "${VP_NAMESPACE:=vp}" # Namespace for the local Vault playground, used for network and container names

if [ ! $(command -v docker) ]; then
  echo -e "\ndocker not found! It must be installed before proceeding: https://www.docker.com/get-docker\n"
  exit 1
fi

docker ps -f network=$VP_NAMESPACE