#!/usr/bin/env bash

source aserta

echo "Running make help should give information about every task in the Makefile"
assert_str_equals    $(grep -c [^PHONY+\"]: ../Makefile) $(cd ../ && exec make help | wc -l)

assert_end "make help"